#!/usr/bin/env bash

while getopts d: OPT
do
  case $OPT in
    d)
      delimiter="$OPTARG"
      ;;
    *)
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

head -n1 | tr "${delimiter:?}" '\n' | nl -w 2 -s' '
